#!/bin/bash

declare -a citydb_versions=("v3.0.0" "v3.1.0" "v3.2.0" "v3.3.0" "v3.3.1")
scripts='CREATE_DB.sql 3dcitydb.sh addcitydb dropcitydb purgedb'

for i in "${citydb_versions[@]}"
do
  version="${i}"
  version_alpine="${i}/alpine"
  df_version=${version}/Dockerfile
  df_version_alpine=${version_alpine}/Dockerfile
  echo $version
  echo $version_alpine
  
  # clear existing version folder
  rm -rf ${version}
  mkdir -p ${version}
  mkdir -p ${version_alpine}
    
  # template -> Dockerfile, replace %%CITYDB_VERSION%% in template
  sed -e "s/%%CITYDB_VERSION%%/${version}/g" Dockerfile-debian.template > ${df_version}
  sed -e "s/%%CITYDB_VERSION%%/${version}/g" Dockerfile-alpine.template > ${df_version_alpine}
  
  # copy scripts
  cp $scripts ${version}
  cp $scripts ${version_alpine}
  
  git add ${version} ${version_alpine}
  
done